// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package iot

import (
	"yumikokawaii.iot.com/config"
	"yumikokawaii.iot.com/db"
	"yumikokawaii.iot.com/pkg/auth"
	"yumikokawaii.iot.com/pkg/devices"
	"yumikokawaii.iot.com/pkg/mqttresolver"
	"yumikokawaii.iot.com/pkg/userinfo"
)

// Injectors from wire.go:

func Initialize(cfg *config.AppConfig) *ServiceServer {
	gormDB := db.NewMySQLDB(cfg)
	repository := userinfo.NewRepository(gormDB)
	service := userinfo.NewService(repository)
	devicesRepository := devices.NewRepository(gormDB)
	publisher := mqttresolver.NewPublisher(cfg)
	devicesService := devices.NewService(devicesRepository, publisher)
	jwtResolver := auth.NewJWTResolver(cfg)
	subscriber := mqttresolver.NewSubscriber(cfg)
	serviceServer := NewServiceServer(service, devicesService, jwtResolver, subscriber)
	return serviceServer
}
